In [3]:
import pandas as pd
import numpy as np
weather_data = {
    'day' : ['1/5/2024','5/4/2025','6/2/2023','5/5/2028','7/10/2025','3/5/2029'],
    'temperature' : [32,35,28,24,27,41],
    'windspeed' : [6,8,7,2,1,5],
    'event' : ['rain','sunny','snow','snow','rain','sunny']
}

In [4]:
#1) Create a Dataframe
df = pd.DataFrame(weather_data)
print(df)

         day  temperature  windspeed  event
0   1/5/2024           32          6   rain
1   5/4/2025           35          8  sunny
2   6/2/2023           28          7   snow
3   5/5/2028           24          2   snow
4  7/10/2025           27          1   rain
5   3/5/2029           41          5  sunny

In [6]:
#2) Print Shape
df.shape

(6, 4)

In [7]:
r,c = df.shape
print(r)
print(c)

6
4

In [8]:
#4) print first five records
df.head()

         day  temperature  windspeed  event
0   1/5/2024           32          6   rain
1   5/4/2025           35          8  sunny
2   6/2/2023           28          7   snow
3   5/5/2028           24          2   snow
4  7/10/2025           27          1   rain

In [9]:
#5) print last five records
df.tail()

         day  temperature  windspeed  event
1   5/4/2025           35          8  sunny
2   6/2/2023           28          7   snow
3   5/5/2028           24          2   snow
4  7/10/2025           27          1   rain
5   3/5/2029           41          5  sunny

In [10]:
#4) print first two records
df.head(2)

        day  temperature  windspeed  event
0  1/5/2024           32          6   rain
1  5/4/2025           35          8  sunny

In [11]:
#5) print last three records
df.tail(3)

         day  temperature  windspeed  event
3   5/5/2028           24          2   snow
4  7/10/2025           27          1   rain
5   3/5/2029           41          5  sunny

In [13]:
#6) print row : 2 to row : 4
df.iloc[2:4]

        day  temperature  windspeed event
2  6/2/2023           28          7  snow
3  5/5/2028           24          2  snow

In [14]:
#7) print name of columns
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [16]:
#8) print maximum temperature
df['temperature'].max()

41

In [17]:
#9) print minimum temperature
df['temperature'].min()

24

In [18]:
#10) print average temperature
df['temperature'].mean()

31.166666666666668

In [19]:
#11) use df.describe() command
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     31.166667   4.833333
std       6.177918   2.786874
min      24.000000   1.000000
25%      27.250000   2.750000
50%      30.000000   5.500000
75%      34.250000   6.750000
max      41.000000   8.000000

In [23]:
#12) print records for temperature gr. th. 32
df[df['temperature']>32]

        day  temperature  windspeed  event
1  5/4/2025           35          8  sunny
5  3/5/2029           41          5  sunny

In [25]:
#13) print record for max. temperature
df[df['temperature'] == df['temperature'].max()]

        day  temperature  windspeed  event
5  3/5/2029           41          5  sunny

In [30]:
#14) displaying date when max temp 
df['day'][df.temperature == df.temperature.max()]

5    3/5/2029
Name: day, dtype: object

In [33]:
df[['day','windspeed','temperature']][df.temperature == df.temperature.max()]

        day  windspeed  temperature
5  3/5/2029          5           41

In [37]:
#15) change index column to event
df.set_index('event',inplace=True)
df

             day  temperature  windspeed
event
rain    1/5/2024           32          6
sunny   5/4/2025           35          8
snow    6/2/2023           28          7
snow    5/5/2028           24          2
rain   7/10/2025           27          1
sunny   3/5/2029           41          5

In [40]:
#16) reset index column as index column
df.reset_index(inplace=True)
df

   level_0  index  event        day  temperature  windspeed
0        0      0   rain   1/5/2024           32          6
1        1      1  sunny   5/4/2025           35          8
2        2      2   snow   6/2/2023           28          7
3        3      3   snow   5/5/2028           24          2
4        4      4   rain  7/10/2025           27          1
5        5      5  sunny   3/5/2029           41          5