In [2]:
import pandas as pd
df=pd.read_csv('dataset//weather_data.csv')
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [3]:
new_df= df.fillna(0)
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          0.0        9.0   Sunny
2   1/5/2017         28.0        0.0    Snow
3   1/6/2017          0.0        7.0       0
4   1/7/2017         32.0        0.0    Rain
5   1/8/2017          0.0        0.0   Sunny
6   1/9/2017          0.0        0.0       0
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [5]:
new_df= df.fillna({
    'temperature' : 0,
    'windspeed' : 'no wind',
    'event' : 'no event'
})
new_df

         day  temperature windspeed     event
0   1/1/2017         32.0       6.0      Rain
1   1/4/2017          0.0       9.0     Sunny
2   1/5/2017         28.0   no wind      Snow
3   1/6/2017          0.0       7.0  no event
4   1/7/2017         32.0   no wind      Rain
5   1/8/2017          0.0   no wind     Sunny
6   1/9/2017          0.0   no wind  no event
7  1/10/2017         34.0       8.0    Cloudy
8  1/11/2017         40.0      12.0     Sunny

In [6]:
new_df = df.ffill()    ## Forward fill 
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        9.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         32.0        7.0   Sunny
6   1/9/2017         32.0        7.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [7]:
new_df = df.bfill()    ## Backward fill
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         28.0        9.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         32.0        7.0    Rain
4   1/7/2017         32.0        8.0    Rain
5   1/8/2017         34.0        8.0   Sunny
6   1/9/2017         34.0        8.0  Cloudy
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [9]:
new_df = df.bfill(axis="columns")
new_df

         day temperature windspeed   event
0   1/1/2017        32.0       6.0    Rain
1   1/4/2017         9.0       9.0   Sunny
2   1/5/2017        28.0      Snow    Snow
3   1/6/2017         7.0       7.0     NaN
4   1/7/2017        32.0      Rain    Rain
5   1/8/2017       Sunny     Sunny   Sunny
6   1/9/2017         NaN       NaN     NaN
7  1/10/2017        34.0       8.0  Cloudy
8  1/11/2017        40.0      12.0   Sunny

In [11]:
new_df = df.ffill(axis="rows")
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        9.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         32.0        7.0   Sunny
6   1/9/2017         32.0        7.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [12]:
new_df= df.dropna()
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny