In [1]:
import pandas as pd
import numpy as np

In [3]:
gujarat_weather = pd.DataFrame({
    "city" : ["baroda","godhra","bharuch"],
    "temperature" : [32,40,30],
    "humidity" : [80,60,70]
})
gujarat_weather

      city  temperature  humidity
0   baroda           32        80
1   godhra           40        60
2  bharuch           30        70

In [4]:
maharastra_weather = pd.DataFrame({
    "city" : ["mumbai","pune","nagpur"],
    "temperature" : [30,35,40],
    "humidity" : [80,60,50]
})
maharastra_weather

     city  temperature  humidity
0  mumbai           30        80
1    pune           35        60
2  nagpur           40        50

In [7]:
df = pd.concat([gujarat_weather,maharastra_weather ],ignore_index= True)       ## concat --> for merge data  
df                                                                             ##ignore_index= True --> it will ignore the index value and give the original numbers

      city  temperature  humidity
0   baroda           32        80
1   godhra           40        60
2  bharuch           30        70
3   mumbai           30        80
4     pune           35        60
5   nagpur           40        50

In [8]:
df = pd.concat([gujarat_weather,maharastra_weather ],keys=["Guj","Maha"])        ## Key will give the main column name 
df

           city  temperature  humidity
Guj  0   baroda           32        80
     1   godhra           40        60
     2  bharuch           30        70
Maha 0   mumbai           30        80
     1     pune           35        60
     2   nagpur           40        50

In [9]:
df.loc["Guj"]

      city  temperature  humidity
0   baroda           32        80
1   godhra           40        60
2  bharuch           30        70

In [10]:
df.loc["Maha"]

     city  temperature  humidity
0  mumbai           30        80
1    pune           35        60
2  nagpur           40        50

In [13]:
temperature_df= pd.DataFrame({
    "city" : ["mumbai","delhi","baglore"],
    "temperature" : [32,45,30]
})
temperature_df.index=[10,11,22]
temperature_df

       city  temperature
10   mumbai           32
11    delhi           45
22  baglore           30

In [14]:
windspeed_df=pd.DataFrame({
    "city" : ["delhi","mumbai"],
    "windspeed" : [7,12]
})
windspeed_df

     city  windspeed
0   delhi          7
1  mumbai         12

In [ ]:
df = pd.concat([temperature_df,windspeed_df],ignore_index= True)  
df.index 
df