In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.DataFrame({
    "city" : ["new york","chicago","orland"],
    "temperature" : [32,14,20]
})
df1

       city  temperature
0  new york           32
1   chicago           14
2    orland           20

In [3]:
df2 = pd.DataFrame({
    "city" : ["chicago","new york","orland"],
    "humidity" : [65,68,75]
})
df2

       city  humidity
0   chicago        65
1  new york        68
2    orland        75

In [4]:
df3 = pd.merge(df1,df2,on="city")           ## merge --> used to merge dataframes
df3

       city  temperature  humidity
0  new york           32        68
1   chicago           14        65
2    orland           20        75

In [5]:
df1 = pd.DataFrame({
    "city" : ["chicago","new york","orland","baltimore"],
    "temperature" : [32,14,20,38]
})
df1

        city  temperature
0    chicago           32
1   new york           14
2     orland           20
3  baltimore           38

In [6]:
df2 = pd.DataFrame({
    "city" : ["chicago","new york","sand diego"],
    "humidity" : [65,68,75]
})
df2

         city  humidity
0     chicago        65
1    new york        68
2  sand diego        75

In [8]:
df3 = pd.merge(df1,df2,on="city",how="outer")           ## outer join
df3

         city  temperature  humidity
0   baltimore         38.0       NaN
1     chicago         32.0      65.0
2    new york         14.0      68.0
3      orland         20.0       NaN
4  sand diego          NaN      75.0

In [9]:
df3 = pd.merge(df1,df2,on="city",how="inner")            ## inner join
df3

       city  temperature  humidity
0   chicago           32        65
1  new york           14        68

In [10]:
df3 = pd.merge(df1,df2,on="city",how="left")             ## left outer join
df3

        city  temperature  humidity
0    chicago           32      65.0
1   new york           14      68.0
2     orland           20       NaN
3  baltimore           38       NaN

In [11]:
df3 = pd.merge(df1,df2,on="city",how="right")            ## right outer join
df3

         city  temperature  humidity
0     chicago         32.0        65
1    new york         14.0        68
2  sand diego          NaN        75

In [12]:
df3 = pd.merge(df1,df2,on="city",how="outer",indicator=True)            ## indicator 
df3

         city  temperature  humidity      _merge
0   baltimore         38.0       NaN   left_only
1     chicago         32.0      65.0        both
2    new york         14.0      68.0        both
3      orland         20.0       NaN   left_only
4  sand diego          NaN      75.0  right_only