In [16]:
import pandas as pd
import numpy as np

df = pd.read_csv('dataset/FoodOrderDetails.csv')
df

     1/1/2017   Burger    10  1000 10000
0    1/2/2017   Nofood     5  n.a.  5000
1    1/3/2017   Franky    11   500  5500
2    1/4/2018   Nofood     0  n.a.   800
3    5/9/2020   Samosa    20    15     0
4     missing  Kachori     0    10    30
5  11/12/2022     Dosa     5  n.a.     0
6   10/9/2023    Momos    10    10   100
7     missing   Nofood  n.a.    30  n.a.
8  15/12/2024  Paratha   100    30  3000

In [17]:
# 1)Display Data
df = pd.read_csv('dataset/FoodOrderDetails.csv')
df

     1/1/2017   Burger    10  1000 10000
0    1/2/2017   Nofood     5  n.a.  5000
1    1/3/2017   Franky    11   500  5500
2    1/4/2018   Nofood     0  n.a.   800
3    5/9/2020   Samosa    20    15     0
4     missing  Kachori     0    10    30
5  11/12/2022     Dosa     5  n.a.     0
6   10/9/2023    Momos    10    10   100
7     missing   Nofood  n.a.    30  n.a.
8  15/12/2024  Paratha   100    30  3000

In [18]:
## 2)Remove Header
df = pd.read_csv('dataset/FoodOrderDetails.csv',header = None)
df

            0        1     2     3      4
0    1/1/2017   Burger    10  1000  10000
1    1/2/2017   Nofood     5  n.a.   5000
2    1/3/2017   Franky    11   500   5500
3    1/4/2018   Nofood     0  n.a.    800
4    5/9/2020   Samosa    20    15      0
5     missing  Kachori     0    10     30
6  11/12/2022     Dosa     5  n.a.      0
7   10/9/2023    Momos    10    10    100
8     missing   Nofood  n.a.    30   n.a.
9  15/12/2024  Paratha   100    30   3000

In [19]:
## 3)Give Header As "OrdDate","Name","Qty","Price","Total"
df = pd.read_csv("data/FoodOrderDetails.csv", names=["OrdDate","Name","Qty","Price","Total"])
df

FileNotFoundError: [Errno 2] No such file or directory: 'data\\FoodOrderDetails.csv'

In [ ]:
## 4)Replace 0 and n.a. with NaN
df = pd.read_csv("data\\FoodOrderDetails.csv", names=["OrdDate","Name","Qty","Price","Total"],na_values=["0","n.a."])
df

In [20]:
## 5) replace missing values in OrdDate Column with ##/##/#####
df['OrdDate'].replace('missing','##/##/####',inplace=True)
df

KeyError: 'OrdDate'

In [7]:
## 6) Replace Nofood with Panipuri from Name column
df['Name'].replace('Nofood','Panipuri',inplace=True)
df

      OrdDate      Name  Qty Price  Total
0    1/1/2017    Burger   10  1000  10000
1    1/2/2017  Panipuri    5   NaN   5000
2    1/3/2017    Franky   11   500   5500
3    1/4/2018  Panipuri  NaN   NaN    800
4    5/9/2020    Samosa   20    15    NaN
5  ##/##/####   Kachori  NaN    10     30
6  11/12/2022      Dosa    5   NaN    NaN
7   10/9/2023     Momos   10    10    100
8  ##/##/####  Panipuri  NaN    30    NaN
9  15/12/2024   Paratha  100    30   3000

In [8]:
## 4)Replace 0 and n.a. with NaN
df = pd.read_csv("data\\FoodOrderDetails.csv", names=["OrdDate","Name","Qty","Price","Total"],na_values=["0","n.a."])
df

      OrdDate      Name  Qty Price  Total
0    1/1/2017    Burger   10  1000  10000
1    1/2/2017  Panipuri    5     0   5000
2    1/3/2017    Franky   11   500   5500
3    1/4/2018  Panipuri    0     0    800
4    5/9/2020    Samosa   20    15      0
5  ##/##/####   Kachori    0    10     30
6  11/12/2022      Dosa    5     0      0
7   10/9/2023     Momos   10    10    100
8  ##/##/####  Panipuri    0    30      0
9  15/12/2024   Paratha  100    30   3000

In [9]:
## 7) Replae NaN value with 0 in Column Qty, Price and Total
df[['Qty', 'Price','Total']] = df[['Qty', 'Price','Total']].fillna(value=0)
df

      OrdDate      Name  Qty Price  Total
0    1/1/2017    Burger   10  1000  10000
1    1/2/2017  Panipuri    5     0   5000
2    1/3/2017    Franky   11   500   5500
3    1/4/2018  Panipuri    0     0    800
4    5/9/2020    Samosa   20    15      0
5  ##/##/####   Kachori    0    10     30
6  11/12/2022      Dosa    5     0      0
7   10/9/2023     Momos   10    10    100
8  ##/##/####  Panipuri    0    30      0
9  15/12/2024   Paratha  100    30   3000

In [10]:
## 8)Any row with Qty = 0, then Total should also be equal to 0
df.loc[df["Qty"] == 0, "Total"] = 0
df

      OrdDate      Name  Qty Price  Total
0    1/1/2017    Burger   10  1000  10000
1    1/2/2017  Panipuri    5     0   5000
2    1/3/2017    Franky   11   500   5500
3    1/4/2018  Panipuri    0     0      0
4    5/9/2020    Samosa   20    15      0
5  ##/##/####   Kachori    0    10      0
6  11/12/2022      Dosa    5     0      0
7   10/9/2023     Momos   10    10    100
8  ##/##/####  Panipuri    0    30      0
9  15/12/2024   Paratha  100    30   3000

In [11]:
## 9)Any row with Price = 0, then Total should also be equal to 0
df.loc[(df["Qty"] == 0) | (df["Price"] == 0), "Total"] = 0
df

      OrdDate      Name  Qty Price  Total
0    1/1/2017    Burger   10  1000  10000
1    1/2/2017  Panipuri    5     0      0
2    1/3/2017    Franky   11   500   5500
3    1/4/2018  Panipuri    0     0      0
4    5/9/2020    Samosa   20    15      0
5  ##/##/####   Kachori    0    10      0
6  11/12/2022      Dosa    5     0      0
7   10/9/2023     Momos   10    10    100
8  ##/##/####  Panipuri    0    30      0
9  15/12/2024   Paratha  100    30   3000

In [12]:
## 10) Display records with 0 Qty
x = df[df.Qty == 0]
x

      OrdDate      Name Qty Price Total
3    1/4/2018  Panipuri   0     0     0
5  ##/##/####   Kachori   0    10     0
8  ##/##/####  Panipuri   0    30     0

In [13]:
## 11) Display records with 0 Price
x = df[df.Price == 0]
x

      OrdDate      Name Qty Price Total
1    1/2/2017  Panipuri   5     0     0
3    1/4/2018  Panipuri   0     0     0
6  11/12/2022      Dosa   5     0     0

In [14]:
## 12) Display records with Total > 0
## 12) Display records with Total > 0
x = df[df.Total > 0]
x

      OrdDate     Name  Qty  Price  Total
0    1/1/2017   Burger   10   1000  10000
2    1/3/2017   Franky   11    500   5500
7   10/9/2023    Momos   10     10    100
9  15/12/2024  Paratha  100     30   3000

In [15]:
## 13) Display records with 0 Qty , Price and Total
x = df[(df.Qty == 0) & (df.Price == 0)  & (df.Total == 0)]
x

Empty DataFrame
Columns: [OrdDate, Name, Qty, Price, Total]
Index: []

In [ ]:
## 14)Drop all records with 0 in Qty,Price,Total
df = df[(df.Qty != 0) & (df.Price != 0)  & (df.Total != 0)]
df

In [ ]:
## 15) Create a csv file "FoodOrderDetailsPreprocessed.csv" in data folder
df.to_csv("data\\FoodOrderDetailsPreprocessed.csv")
df

In [ ]:
## 16) Display Data
df = pd.read_csv("data\\FoodOrderDetailsPreprocessed.csv")
df

In [ ]:
## 17) drop column Unnamed: 0
df.drop('Unnamed: 0',axis=1,inplace=True)
df